name: 🐛 Bug Report
description: Signaler un bug ou un dysfonctionnement dans Batistack
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Merci de signaler ce bug ! Votre rapport nous aide à améliorer Batistack.

        **Avant de continuer, vérifiez que :**
        - [ ] Ce bug n'a pas déjà été signalé
        - [ ] Vous utilisez la dernière version de Batistack
        - [ ] Vous avez testé sur un environnement propre

  - type: dropdown
    id: module
    attributes:
      label: 🏗️ Module concerné
      description: Dans quel module le bug se produit-il ?
      options:
        - "🏗️ Chantiers"
        - "👥 RH (Ressources Humaines)"
        - "🏢 Tiers (Clients/Fournisseurs)"
        - "💰 Commerce (Devis/Factures)"
        - "📦 Produits & Services"
        - "⚙️ Core (Infrastructure)"
        - "🖥️ Interface/UI"
        - "🔐 Authentification"
        - "📱 Application Desktop (Tauri)"
        - "🌐 API"
        - "❓ Je ne sais pas"
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: 🚨 Sévérité
      description: Quel est l'impact de ce bug ?
      options:
        - "🔴 Critique - Bloque l'utilisation"
        - "🟠 Majeur - Fonctionnalité importante cassée"
        - "🟡 Mineur - Gêne mais contournable"
        - "🔵 Cosmétique - Problème d'affichage"
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: 🌍 Environnement
      description: Sur quel environnement le bug se produit-il ?
      options:
        - "🌐 Web (navigateur)"
        - "🖥️ Desktop (Tauri)"
        - "📱 Mobile/PWA"
        - "🧪 Test/Staging"
        - "🏭 Production"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 📝 Description du bug
      description: Décrivez clairement le problème rencontré
      placeholder: |
        Exemple : Lors de la création d'un nouveau chantier, le formulaire ne se soumet pas et affiche une erreur 500.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 🔄 Étapes pour reproduire
      description: Comment reproduire ce bug ?
      placeholder: |
        1. Aller sur la page "Chantiers"
        2. Cliquer sur "Nouveau chantier"
        3. Remplir le formulaire avec...
        4. Cliquer sur "Enregistrer"
        5. Observer l'erreur
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ✅ Comportement attendu
      description: Que devrait-il se passer normalement ?
      placeholder: Le chantier devrait être créé et je devrais être redirigé vers sa fiche.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: ❌ Comportement observé
      description: Que se passe-t-il réellement ?
      placeholder: Une erreur 500 s'affiche et le chantier n'est pas créé.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 📋 Logs/Messages d'erreur
      description: Copiez ici les logs ou messages d'erreur (si disponibles)
      render: shell
      placeholder: |
        [2025-01-XX XX:XX:XX] local.ERROR: ...

        Ou capture d'écran de l'erreur

  - type: input
    id: version
    attributes:
      label: 📦 Version de Batistack
      description: Quelle version utilisez-vous ?
      placeholder: "v1.12.0"
    validations:
      required: true

  - type: textarea
    id: browser
    attributes:
      label: 🌐 Informations navigateur/système
      description: Navigateur, OS, version...
      placeholder: |
        - OS: Windows 11
        - Navigateur: Chrome 120.0.0.0
        - Résolution: 1920x1080
        - Version PHP: 8.3
        - Version Laravel: 11.x

  - type: textarea
    id: additional
    attributes:
      label: ➕ Informations supplémentaires
      description: Tout autre détail utile (captures d'écran, workarounds, etc.)
      placeholder: |
        - Captures d'écran
        - Contournement possible
        - Fréquence du problème
        - Impact sur les utilisateurs

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Checklist
      options:
        - label: J'ai vérifié que ce bug n'existe pas déjà
          required: true
        - label: J'ai testé sur la dernière version
          required: true
        - label: J'ai fourni toutes les informations nécessaires
          required: true
        - label: J'ai masqué les informations sensibles (mots de passe, tokens, etc.)
          required: true
