name: 🐛 Bug Report
description: Signaler un bug pour nous aider à corriger quelque chose qui ne fonctionne pas
title: "[BUG] "
labels: ["Bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Rapport de Bug - Batistack

        Merci de prendre le temps de signaler ce bug. Vos informations nous aident à améliorer Batistack.

        **Avant de continuer :**
        - [ ] J'ai vérifié que ce bug n'a pas déjà été signalé
        - [ ] J'ai testé avec la dernière version disponible
        - [ ] J'ai des informations suffisantes pour reproduire le problème

        Vous pouvez utiliser la [syntaxe Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) pour formater votre rapport.

  - type: textarea
    id: bug-description
    attributes:
      label: 📝 Description du Bug
      description: Description claire et concise du problème rencontré
      placeholder: "Décrivez ce qui ne fonctionne pas comme attendu..."
    validations:
      required: true

  - type: dropdown
    id: affected-modules
    attributes:
      label: 🏗️ Module(s) Affecté(s)
      description: Sélectionnez le ou les modules concernés par ce bug
      multiple: true
      options:
        - "🏗️ Chantiers"
        - "👥 RH (Ressources Humaines)"
        - "💰 Commerce (Devis/Factures)"
        - "🤝 Tiers (Clients/Fournisseurs)"
        - "🔧 Infrastructure"
        - "📊 Dashboard"
        - "⚙️ Core/Système"
        - "🔐 Authentification"
        - "📱 Interface Utilisateur"
        - "🖥️ Application Desktop (Tauri)"
        - "📄 Génération PDF"
        - "📁 Gestion des médias"
        - "🔔 Notifications"
        - "❓ Non identifié"
    validations:
      required: true

  - type: dropdown
    id: bug-severity
    attributes:
      label: 🚨 Niveau de Gravité
      description: Évaluez l'impact du bug sur votre utilisation
      options:
        - "🔴 Critique - Bloque complètement l'utilisation"
        - "🟠 Élevé - Fonctionnalité importante inutilisable"
        - "🟡 Moyen - Gêne dans l'utilisation quotidienne"
        - "🟢 Faible - Problème mineur ou cosmétique"
    validations:
      required: true

  - type: input
    id: environment-version
    attributes:
      label: 📦 Version Batistack
      description: Version de Batistack affectée
      placeholder: "ex: 1.5.0, develop, master..."
    validations:
      required: true

  - type: input
    id: environment-php
    attributes:
      label: 🐘 Version PHP
      description: Version PHP utilisée
      placeholder: "ex: 8.3.1"

  - type: input
    id: environment-database
    attributes:
      label: 🗄️ Base de Données
      description: Type et version de la base de données
      placeholder: "ex: MySQL 8.0, PostgreSQL 15"

  - type: dropdown
    id: environment-platform
    attributes:
      label: 💻 Plateforme
      description: Sur quelle plateforme le bug se produit-il ?
      options:
        - "🌐 Web (Navigateur)"
        - "🖥️ Desktop (Tauri)"
        - "📱 Mobile (Tauri Mobile)"
        - "🔧 CLI/Artisan"
        - "⚙️ Background Jobs"

  - type: input
    id: browser-info
    attributes:
      label: 🌐 Navigateur (si applicable)
      description: Navigateur et version utilisés
      placeholder: "ex: Chrome 120.0, Firefox 121.0, Safari 17.0"

  - type: textarea
    id: steps-reproduce
    attributes:
      label: 🔄 Étapes pour Reproduire
      description: Décrivez précisément les étapes pour reproduire le bug
      placeholder: |
        1. Aller à '...'
        2. Cliquer sur '...'
        3. Remplir le champ '...'
        4. Voir l'erreur
      value: |
        1.
        2.
        3.
        4.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: ✅ Comportement Attendu
      description: Décrivez ce qui devrait se passer normalement
      placeholder: "Décrivez le comportement attendu..."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: ❌ Comportement Actuel
      description: Décrivez ce qui se passe réellement
      placeholder: "Décrivez ce qui se passe à la place..."
    validations:
      required: true

  - type: textarea
    id: error-messages
    attributes:
      label: 🚫 Messages d'Erreur
      description: Copiez-collez les messages d'erreur complets (logs, console, etc.)
      placeholder: "Collez ici les messages d'erreur, stack traces, logs..."
      render: text

  - type: textarea
    id: additional-context
    attributes:
      label: 📋 Contexte Supplémentaire
      description: Informations additionnelles qui pourraient aider (configuration spéciale, données de test, etc.)
      placeholder: "Ajoutez toute information supplémentaire utile..."

  - type: textarea
    id: files-attachments
    attributes:
      label: 📎 Fichiers Joints
      description: Screenshots, vidéos, logs, fichiers de configuration
      placeholder: |
        Vous pouvez glisser-déposer des fichiers ici ou utiliser des liens.

        Types de fichiers utiles :
        - Screenshots/captures d'écran
        - Vidéos de reproduction du bug
        - Logs Laravel (storage/logs/laravel.log)
        - Logs de la console navigateur
        - Fichiers de configuration (.env masqué)

  - type: checkboxes
    id: additional-checks
    attributes:
      label: ✅ Vérifications Supplémentaires
      description: Cochez les éléments que vous avez vérifiés
      options:
        - label: "J'ai vidé le cache de l'application (`php artisan cache:clear`)"
        - label: "J'ai vidé le cache de configuration (`php artisan config:clear`)"
        - label: "J'ai vérifié les logs Laravel pour des erreurs supplémentaires"
        - label: "J'ai testé avec un autre navigateur/environnement"
        - label: "J'ai vérifié que mes données de test sont valides"
        - label: "J'ai testé en mode développement et production"

  - type: dropdown
    id: willing-to-help
    attributes:
      label: 🤝 Contribution
      description: Seriez-vous disposé(e) à aider à résoudre ce bug ?
      options:
        - "✅ Oui, je peux aider à investiguer"
        - "✅ Oui, je peux tester des corrections"
        - "✅ Oui, je peux proposer une solution"
        - "❓ Peut-être, selon ma disponibilité"
        - "❌ Non, je ne peux pas contribuer"
