name: 🚨 Échec CI/CD
description: Signaler un échec de test ou de déploiement dans les workflows GitHub Actions
title: "[CI] Échec sur "
labels: ["bug", "ci", "urgent"]
assignees: ["vortechstudio"]

body:
  - type: markdown
    attributes:
      value: |
        ## 🚨 Échec de CI/CD détecté

        Utilisez ce template pour signaler un échec dans les workflows GitHub Actions (tests, déploiement, qualité de code, etc.).

  - type: dropdown
    id: workflow_type
    attributes:
      label: Type de workflow en échec
      description: Quel workflow a échoué ?
      options:
        - "🧪 Tests (tests-on-master)"
        - "🔍 Qualité de code (code-quality)"
        - "🏗️ CI Module (module-ci)"
        - "🚀 Déploiement (module-deployment)"
        - "📦 Release (release)"
        - "🤖 Automatisation issues (issue-automation)"
        - "🔒 Fermeture automatique (auto-close-issues)"
        - "Autre workflow"
    validations:
      required: true

  - type: input
    id: branch_name
    attributes:
      label: Branche concernée
      description: Sur quelle branche l'échec s'est-il produit ?
      placeholder: "ex: master, develop, feature/nouvelle-fonctionnalite"
    validations:
      required: true

  - type: input
    id: commit_sha
    attributes:
      label: Commit SHA
      description: Identifiant du commit qui a causé l'échec
      placeholder: "ex: a1b2c3d4e5f6..."
    validations:
      required: true

  - type: input
    id: workflow_run_id
    attributes:
      label: ID du workflow (optionnel)
      description: Lien vers le workflow en échec
      placeholder: "ex: https://github.com/user/repo/actions/runs/123456789"
    validations:
      required: false

  - type: dropdown
    id: failure_type
    attributes:
      label: Type d'échec
      description: Quelle est la nature de l'échec ?
      options:
        - "❌ Tests unitaires en échec"
        - "❌ Tests d'intégration en échec"
        - "🔍 Échec de qualité de code (Pint, PHPStan)"
        - "🚀 Échec de déploiement"
        - "📦 Échec de build/compilation"
        - "🗄️ Échec de migration"
        - "🔧 Erreur de configuration"
        - "⏱️ Timeout"
        - "🌐 Problème de connectivité"
        - "Autre"
    validations:
      required: true

  - type: textarea
    id: error_details
    attributes:
      label: Détails de l'erreur
      description: Copiez les logs d'erreur ou décrivez le problème
      placeholder: |
        Exemple :
        ```
        PHPUnit 10.5.0 by Sebastian Bergmann and contributors.

        F                                                                   1 / 1 (100%)

        Time: 00:00.123, Memory: 24.00 MB

        There was 1 failure:

        1) Tests\Feature\ExampleTest::test_example
        Failed asserting that false is true.
        ```
    validations:
      required: true

  - type: dropdown
    id: affected_modules
    attributes:
      label: Modules affectés
      description: Quels modules sont impactés par cet échec ?
      multiple: true
      options:
        - "🏗️ Chantiers"
        - "👥 RH"
        - "🏢 Tiers"
        - "💼 Commerce"
        - "⚙️ Core"
        - "📦 Produits/Services"
        - "🏭 GPAO"
        - "💰 Facturation"
        - "📊 Comptabilité"
        - "🚗 Véhicules"
        - "📁 GED"
        - "🔧 Infrastructure"
        - "🎨 Frontend"
        - "Tous les modules"
        - "Aucun module spécifique"

  - type: dropdown
    id: urgency
    attributes:
      label: Niveau d'urgence
      description: Quel est l'impact de cet échec ?
      options:
        - "🔴 Critique - Bloque la production"
        - "🟠 Haute - Bloque le développement"
        - "🟡 Moyenne - Impact limité"
        - "🟢 Basse - Peut attendre"
    validations:
      required: true

  - type: checkboxes
    id: impact_assessment
    attributes:
      label: Évaluation de l'impact
      description: Quels sont les impacts de cet échec ?
      options:
        - label: "🚫 Bloque les déploiements"
        - label: "🔒 Bloque les merges vers master"
        - label: "⚠️ Affecte la qualité du code"
        - label: "📊 Impact sur les métriques de couverture"
        - label: "👥 Affecte l'équipe de développement"
        - label: "🏭 Impact sur l'environnement de production"
        - label: "🧪 Impact sur l'environnement de test"

  - type: textarea
    id: reproduction_steps
    attributes:
      label: Étapes de reproduction
      description: Comment reproduire ce problème localement ?
      placeholder: |
        1. Cloner la branche `nom-de-la-branche`
        2. Installer les dépendances avec `composer install`
        3. Exécuter `php artisan test`
        4. Observer l'erreur...
    validations:
      required: false

  - type: textarea
    id: investigation_done
    attributes:
      label: Investigation déjà effectuée
      description: Qu'avez-vous déjà essayé pour résoudre le problème ?
      placeholder: |
        - Vérifié les logs du workflow
        - Testé localement sur ma machine
        - Comparé avec le dernier commit fonctionnel
        - Vérifié les dépendances...
    validations:
      required: false

  - type: textarea
    id: potential_cause
    attributes:
      label: Cause potentielle
      description: Avez-vous une idée de ce qui pourrait causer ce problème ?
      placeholder: |
        - Changement récent dans le code
        - Mise à jour de dépendance
        - Modification de configuration
        - Problème d'environnement...
    validations:
      required: false

  - type: checkboxes
    id: action_items
    attributes:
      label: Actions à effectuer
      description: Cochez les actions nécessaires pour résoudre ce problème
      options:
        - label: "🔍 Analyser les logs détaillés du workflow"
        - label: "🧪 Reproduire l'erreur localement"
        - label: "🔄 Relancer le workflow pour confirmer l'échec"
        - label: "📋 Vérifier les changements récents (git diff)"
        - label: "🔧 Vérifier la configuration des environnements"
        - label: "📦 Vérifier les dépendances et versions"
        - label: "🗄️ Vérifier l'état de la base de données"
        - label: "👥 Notifier l'équipe technique"
        - label: "📚 Mettre à jour la documentation"

  - type: textarea
    id: additional_context
    attributes:
      label: Contexte supplémentaire
      description: Toute information supplémentaire utile
      placeholder: |
        - Liens vers des issues similaires
        - Historique des échecs récents
        - Informations sur l'environnement
        - Contraintes de temps...
    validations:
      required: false
