name: 🏗️ Module Development
description: Planifier le développement d'un nouveau module ou l'évolution d'un module existant
title: "[MODULE] "
labels: ["module", "development", "epic"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Ce template est destiné à planifier le développement de modules dans Batistack.

        **Types de modules supportés :**
        - 🏗️ Chantiers, 👥 RH, 🏢 Tiers, 💰 Commerce, 📦 Produits, ⚙️ Core

        **Architecture modulaire :**
        - Chaque module suit la structure Laravel/Livewire
        - Tests automatisés par module (CI/CD)
        - Documentation intégrée

  - type: dropdown
    id: module_type
    attributes:
      label: 🎯 Type de développement
      description: S'agit-il d'un nouveau module ou de l'évolution d'un existant ?
      options:
        - "🆕 Nouveau module"
        - "🔄 Évolution module existant"
        - "🔧 Refactoring module"
        - "🐛 Correction module"
        - "⚡ Optimisation performance"
    validations:
      required: true

  - type: dropdown
    id: target_module
    attributes:
      label: 🏗️ Module cible
      description: Quel module est concerné ?
      options:
        - "🏗️ Chantiers"
        - "👥 RH (Ressources Humaines)"
        - "🏢 Tiers (Clients/Fournisseurs)"
        - "💰 Commerce (Devis/Factures)"
        - "📦 Produits & Services"
        - "⚙️ Core (Infrastructure)"
        - "🆕 Nouveau module à créer"
    validations:
      required: true

  - type: input
    id: module_name
    attributes:
      label: 📛 Nom du module (si nouveau)
      description: Nom du nouveau module (ex: "Véhicules", "GPAO", "Comptabilité")
      placeholder: "Nom du module"

  - type: dropdown
    id: priority
    attributes:
      label: 📊 Priorité roadmap
      description: Quelle est la priorité de ce développement ?
      options:
        - "🔴 P0 - Critique (release bloquante)"
        - "🟠 P1 - Haute (prochaine release)"
        - "🟡 P2 - Moyenne (release future)"
        - "🔵 P3 - Basse (backlog)"
    validations:
      required: true

  - type: textarea
    id: business_context
    attributes:
      label: 💼 Contexte métier
      description: Pourquoi ce module/évolution est-il nécessaire ?
      placeholder: |
        Exemple : Le secteur BTP nécessite une gestion spécialisée des véhicules et engins de chantier avec :
        - Suivi des contrôles techniques
        - Gestion des carnets d'entretien
        - Planification des révisions
        - Suivi consommation carburant
    validations:
      required: true

  - type: textarea
    id: functional_specs
    attributes:
      label: 📋 Spécifications fonctionnelles
      description: Quelles sont les fonctionnalités attendues ?
      placeholder: |
        ## Fonctionnalités principales
        - [ ] Gestion du parc véhicules
        - [ ] Suivi des contrôles techniques
        - [ ] Planification maintenance
        - [ ] Tableau de bord coûts

        ## Intégrations
        - [ ] Module Chantiers (affectation véhicules)
        - [ ] Module RH (conducteurs autorisés)
        - [ ] Module Commerce (facturation kilométrage)
    validations:
      required: true

  - type: textarea
    id: technical_specs
    attributes:
      label: ⚙️ Spécifications techniques
      description: Architecture technique et contraintes
      placeholder: |
        ## Modèles Eloquent
        - Vehicule (id, immatriculation, type, marque, modèle...)
        - VehiculeEntretien (id, vehicule_id, type, date, cout...)
        - VehiculeAffectation (id, vehicule_id, chantier_id, employe_id...)

        ## Composants Livewire
        - VehiculeTable (liste des véhicules)
        - VehiculeForm (création/édition)
        - VehiculeEntretienTable (historique maintenance)

        ## Migrations
        - create_vehicules_table
        - create_vehicule_entretiens_table
        - create_vehicule_affectations_table

        ## Tests
        - VehiculeTest (CRUD)
        - VehiculeEntretienTest (logique métier)
        - VehiculePerformanceTest (requêtes N+1)
    validations:
      required: true

  - type: textarea
    id: database_schema
    attributes:
      label: 🗄️ Schéma base de données
      description: Structure des tables et relations
      render: sql
      placeholder: |
        -- Table principale
        CREATE TABLE vehicules (
            id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            immatriculation VARCHAR(20) UNIQUE NOT NULL,
            type ENUM('voiture', 'camion', 'engin') NOT NULL,
            marque VARCHAR(100) NOT NULL,
            modele VARCHAR(100) NOT NULL,
            annee YEAR NOT NULL,
            created_at TIMESTAMP NULL,
            updated_at TIMESTAMP NULL
        );

        -- Relations
        ALTER TABLE vehicule_affectations
        ADD FOREIGN KEY (vehicule_id) REFERENCES vehicules(id);

  - type: textarea
    id: ui_mockups
    attributes:
      label: 🎨 Maquettes UI/UX
      description: Captures d'écran, wireframes ou liens vers les maquettes
      placeholder: |
        Ajoutez ici :
        - Captures d'écran des interfaces
        - Liens Figma/Sketch
        - Wireframes papier scannés
        - Références d'autres applications

  - type: textarea
    id: testing_strategy
    attributes:
      label: 🧪 Stratégie de tests
      description: Plan de tests pour ce module
      placeholder: |
        ## Tests unitaires
        - [ ] Modèles Eloquent (relations, scopes, mutators)
        - [ ] Services métier (calculs, validations)
        - [ ] Helpers et utilitaires

        ## Tests d'intégration
        - [ ] Composants Livewire (rendu, interactions)
        - [ ] Workflows complets (création → modification → suppression)
        - [ ] Intégrations inter-modules

        ## Tests de performance
        - [ ] Requêtes N+1 (eager loading)
        - [ ] Temps de réponse des pages
        - [ ] Charge mémoire

        ## Tests fonctionnels
        - [ ] Parcours utilisateur complets
        - [ ] Gestion des erreurs
        - [ ] Validation des formulaires

  - type: textarea
    id: migration_plan
    attributes:
      label: 🔄 Plan de migration (si applicable)
      description: Comment migrer les données existantes ?
      placeholder: |
        Si ce module remplace ou étend des fonctionnalités existantes :
        - Migration des données existantes
        - Compatibilité ascendante
        - Plan de rollback
        - Communication aux utilisateurs

  - type: input
    id: estimated_effort
    attributes:
      label: ⏱️ Effort estimé
      description: Estimation en jours/homme
      placeholder: "Ex: 15 jours/homme"

  - type: textarea
    id: dependencies
    attributes:
      label: 🔗 Dépendances
      description: Quelles sont les dépendances de ce développement ?
      placeholder: |
        ## Dépendances techniques
        - [ ] Nouveau package Composer : xyz/package
        - [ ] Mise à jour Laravel vers version X
        - [ ] Configuration serveur spécifique

        ## Dépendances fonctionnelles
        - [ ] Module Chantiers doit être finalisé
        - [ ] API externe à intégrer
        - [ ] Formation équipe nécessaire

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: ✅ Critères d'acceptation
      description: Comment savoir que le développement est terminé ?
      placeholder: |
        ## Critères fonctionnels
        - [ ] Toutes les user stories sont implémentées
        - [ ] Interface utilisateur validée par l'équipe métier
        - [ ] Intégrations avec modules existants fonctionnelles

        ## Critères techniques
        - [ ] Couverture de tests > 80%
        - [ ] Aucune régression détectée
        - [ ] Performance conforme aux standards
        - [ ] Documentation technique à jour

        ## Critères qualité
        - [ ] Code review validé
        - [ ] Standards de codage respectés
        - [ ] Sécurité validée (pas de vulnérabilités)

  - type: checkboxes
    id: ci_cd_integration
    attributes:
      label: 🔄 Intégration CI/CD
      description: Ce module sera-t-il intégré dans les workflows automatisés ?
      options:
        - label: Tests automatisés dans le pipeline CI/CD
          required: true
        - label: Détection automatique des changements du module
          required: true
        - label: Déploiement automatique en staging
          required: false
        - label: Métriques de performance surveillées
          required: false

  - type: checkboxes
    id: documentation
    attributes:
      label: 📚 Documentation
      description: Quelle documentation sera produite ?
      options:
        - label: Documentation utilisateur (guide d'utilisation)
          required: true
        - label: Documentation technique (architecture, API)
          required: true
        - label: Guide de migration (si applicable)
          required: false
        - label: Tutoriels vidéo
          required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Checklist développement
      options:
        - label: Les spécifications sont complètes et validées
          required: true
        - label: L'architecture respecte les standards du projet
          required: true
        - label: Les impacts sur les modules existants sont identifiés
          required: true
        - label: La stratégie de tests est définie
          required: true
        - label: Les critères d'acceptation sont mesurables
          required: true
