name: 🚀 Problème de Performance
description: Signaler un problème de performance ou d'optimisation
title: "[PERF] "
labels: ["performance", "optimization"]

body:
  - type: dropdown
    id: performance_type
    attributes:
      label: Type de problème
      options:
        - "🐌 Lenteur de page"
        - "🗄️ Requêtes N+1"
        - "💾 Utilisation mémoire excessive"
        - "⏱️ Timeout"
        - "📊 Requête SQL lente"
    validations:
      required: true

  - type: textarea
    id: metrics
    attributes:
      label: Métriques observées
      placeholder: |
        - Temps de chargement : X secondes
        - Utilisation mémoire : X MB
        - Nombre de requêtes SQL : X
        - Temps d'exécution SQL : X ms
