name: 🏗️ Module CI/CD

on:
  pull_request:
    branches: [develop, master]
    paths:
      - 'app/Models/Commerce/**'
      - 'app/Livewire/Commerce/**'
      - 'database/migrations/*produit*'
      - 'tests/Feature/Commerce/**'
  push:
    branches: [develop]

jobs:
  module-tests:
    name: Tests Module ${{ matrix.module }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [produits, gpao, facturation]

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, bcmath, pdo_mysql

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run module-specific tests
        run: php artisan test --filter=${{ matrix.module }} --coverage-text

      - name: Check module documentation
        run: |
          if [ ! -f "docs/modules/${{ matrix.module }}.md" ]; then
            echo "❌ Documentation manquante pour le module ${{ matrix.module }}"
            exit 1
          fi

  security-scan:
    name: 🔒 Analyse de sécurité
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run security audit
        run: composer audit

  performance-check:
    name: ⚡ Vérification des performances
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for N+1 queries
        run: php artisan test --filter=Performance
