name: 🚨 Auto-création d'issues pour échecs CI/CD

on:
  workflow_run:
    workflows:
      - "Test sur master"
      - "🏗️ Module CI/CD"
      - "Code Quality"
      - "🚀 Module Deployment"
      - "Semantic Release"
    types:
      - completed

jobs:
  create-failure-issue:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get workflow details
        id: workflow-details
        uses: actions/github-script@v7
        with:
          script: |
            const workflowRun = context.payload.workflow_run;

            // Mapper les noms de workflows vers les types
            const workflowTypeMap = {
              'Test sur master': '🧪 Tests (tests-on-master)',
              '🏗️ Module CI/CD': '🏗️ CI Module (module-ci)',
              'Code Quality': '🔍 Qualité de code (code-quality)',
              '🚀 Module Deployment': '🚀 Déploiement (module-deployment)',
              'Semantic Release': '📦 Release (release)'
            };

            // Déterminer le type d'échec basé sur le nom du workflow
            let failureType = 'Autre';
            const workflowName = workflowRun.name;

            if (workflowName.includes('Test') || workflowName.includes('CI')) {
              failureType = '❌ Tests unitaires en échec';
            } else if (workflowName.includes('Quality')) {
              failureType = '🔍 Échec de qualité de code (Pint, PHPStan)';
            } else if (workflowName.includes('Deployment')) {
              failureType = '🚀 Échec de déploiement';
            } else if (workflowName.includes('Release')) {
              failureType = '📦 Échec de build/compilation';
            }

            // Déterminer l'urgence basée sur la branche
            let urgency = '🟡 Moyenne - Impact limité';
            if (workflowRun.head_branch === 'master' || workflowRun.head_branch === 'main') {
              urgency = '🔴 Critique - Bloque la production';
            } else if (workflowRun.head_branch === 'develop') {
              urgency = '🟠 Haute - Bloque le développement';
            }

            // Analyser les modules affectés basés sur les fichiers modifiés
            let affectedModules = ['Aucun module spécifique'];

            // Si c'est un workflow de module, essayer de détecter le module
            if (workflowName.includes('Module')) {
              // Cette logique pourrait être améliorée en analysant les fichiers modifiés
              affectedModules = ['Tous les modules'];
            }

            return {
              workflowType: workflowTypeMap[workflowName] || 'Autre workflow',
              failureType: failureType,
              urgency: urgency,
              affectedModules: affectedModules,
              workflowUrl: workflowRun.html_url,
              commitSha: workflowRun.head_sha.substring(0, 8),
              branch: workflowRun.head_branch
            };

      - name: Get workflow logs
        id: get-logs
        uses: actions/github-script@v7
        with:
          script: |
            const workflowRun = context.payload.workflow_run;

            try {
              // Récupérer les jobs du workflow
              const jobs = await github.rest.actions.listJobsForWorkflowRun({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: workflowRun.id
              });

              let errorDetails = '';

              // Trouver les jobs en échec
              const failedJobs = jobs.data.jobs.filter(job => job.conclusion === 'failure');

              if (failedJobs.length > 0) {
                errorDetails = `## Jobs en échec:\n\n`;

                for (const job of failedJobs.slice(0, 3)) { // Limiter à 3 jobs pour éviter un texte trop long
                  errorDetails += `### ${job.name}\n`;
                  errorDetails += `- **Statut**: ${job.conclusion}\n`;
                  errorDetails += `- **Durée**: ${Math.round((new Date(job.completed_at) - new Date(job.started_at)) / 1000)}s\n`;

                  // Récupérer les logs du job (limité car l'API peut être volumineuse)
                  try {
                    const logs = await github.rest.actions.downloadJobLogsForWorkflowRun({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      job_id: job.id
                    });

                    // Note: Les logs sont en format binaire, on ne peut pas les traiter directement ici
                    errorDetails += `- **Logs**: [Voir les logs complets](${job.html_url})\n\n`;
                  } catch (error) {
                    errorDetails += `- **Logs**: [Voir les logs complets](${job.html_url})\n\n`;
                  }
                }
              } else {
                errorDetails = `Workflow en échec: ${workflowRun.name}\n\nVoir les détails complets: ${workflowRun.html_url}`;
              }

              return errorDetails;
            } catch (error) {
              return `Erreur lors de la récupération des logs: ${error.message}\n\nVoir le workflow: ${workflowRun.html_url}`;
            }

      - name: Check for existing issue
        id: check-existing
        uses: actions/github-script@v7
        with:
          script: |
            const workflowRun = context.payload.workflow_run;
            const searchQuery = `repo:${context.repo.owner}/${context.repo.repo} is:issue is:open label:ci "[CI] Échec sur ${workflowRun.name}"`;

            const issues = await github.rest.search.issuesAndPullRequests({
              q: searchQuery
            });

            // Vérifier s'il y a une issue récente (moins de 24h) pour le même workflow
            const recentIssues = issues.data.items.filter(issue => {
              const createdAt = new Date(issue.created_at);
              const now = new Date();
              const hoursDiff = (now - createdAt) / (1000 * 60 * 60);
              return hoursDiff < 24;
            });

            return recentIssues.length > 0;

      - name: Create CI failure issue
        if: steps.check-existing.outputs.result == 'false'
        uses: actions/github-script@v7
        with:
          script: |
            const workflowRun = context.payload.workflow_run;
            const details = ${{ steps.workflow-details.outputs.result }};
            const errorLogs = `${{ steps.get-logs.outputs.result }}`;

            // Créer le corps de l'issue en format qui sera traité par le template
            const issueBody = `
            **Type de workflow en échec**: ${details.workflowType}
            **Branche concernée**: ${details.branch}
            **Commit SHA**: ${details.commitSha}
            **ID du workflow**: ${details.workflowUrl}
            **Type d'échec**: ${details.failureType}
            **Niveau d'urgence**: ${details.urgency}
            **Modules affectés**: ${details.affectedModules.join(', ')}

            ## Détails de l'erreur

            ${errorLogs}

            ## Informations du workflow

            - **Workflow**: ${workflowRun.name}
            - **Run ID**: ${workflowRun.id}
            - **Branche**: ${workflowRun.head_branch}
            - **Commit**: ${workflowRun.head_sha}
            - **Auteur**: ${workflowRun.actor.login}
            - **Événement**: ${workflowRun.event}
            - **Heure d'échec**: ${workflowRun.updated_at}

            ## Actions automatiques effectuées

            - ✅ Issue créée automatiquement
            - 🔍 Logs du workflow analysés
            - 🏷️ Labels appropriés ajoutés
            - 👤 Assignation automatique effectuée

            ## Étapes de résolution suggérées

            1. 🔍 Analyser les logs détaillés du workflow
            2. 🧪 Reproduire l'erreur localement
            3. 📋 Vérifier les changements récents (git diff)
            4. 🔧 Vérifier la configuration des environnements
            5. 📦 Vérifier les dépendances et versions

            ---
            *Issue créée automatiquement par le workflow d'automatisation CI/CD*
            `;

            // Créer l'issue
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `[CI] Échec sur ${workflowRun.name} - ${details.branch} (${details.commitSha})`,
              body: issueBody,
              labels: ['bug', 'ci', 'urgent'],
              assignees: ['vortechstudio']
            });

            console.log(`Issue créée: ${issue.data.html_url}`);
            return issue.data.number;

      - name: Add workflow run comment
        if: steps.check-existing.outputs.result == 'false'
        uses: actions/github-script@v7
        with:
          script: |
            const issueNumber = ${{ steps.create-failure-issue.outputs.result }};
            const workflowRun = context.payload.workflow_run;

            if (issueNumber) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: `🔗 **Lien direct vers le workflow en échec**: ${workflowRun.html_url}\n\n` +
                      `📊 **Statistiques du run**:\n` +
                      `- Durée: ${Math.round((new Date(workflowRun.updated_at) - new Date(workflowRun.created_at)) / 1000)}s\n` +
                      `- Tentative: ${workflowRun.run_attempt}\n` +
                      `- ID: ${workflowRun.id}`
              });
            }

      - name: Notify on Slack (if configured)
        if: steps.check-existing.outputs.result == 'false' && vars.SLACK_WEBHOOK_URL
        uses: actions/github-script@v7
        with:
          script: |
            const workflowRun = context.payload.workflow_run;
            const details = ${{ steps.workflow-details.outputs.result }};
            const issueNumber = ${{ steps.create-failure-issue.outputs.result }};

            const slackMessage = {
              text: `🚨 Échec CI/CD détecté`,
              blocks: [
                {
                  type: "header",
                  text: {
                    type: "plain_text",
                    text: "🚨 Échec CI/CD détecté"
                  }
                },
                {
                  type: "section",
                  fields: [
                    {
                      type: "mrkdwn",
                      text: `*Workflow:* ${workflowRun.name}`
                    },
                    {
                      type: "mrkdwn",
                      text: `*Branche:* ${details.branch}`
                    },
                    {
                      type: "mrkdwn",
                      text: `*Commit:* ${details.commitSha}`
                    },
                    {
                      type: "mrkdwn",
                      text: `*Urgence:* ${details.urgency}`
                    }
                  ]
                },
                {
                  type: "actions",
                  elements: [
                    {
                      type: "button",
                      text: {
                        type: "plain_text",
                        text: "Voir le workflow"
                      },
                      url: workflowRun.html_url
                    },
                    {
                      type: "button",
                      text: {
                        type: "plain_text",
                        text: "Voir l'issue"
                      },
                      url: `https://github.com/${context.repo.owner}/${context.repo.repo}/issues/${issueNumber}`
                    }
                  ]
                }
              ]
            };

            // Envoyer à Slack (nécessite la configuration de SLACK_WEBHOOK)
            if (process.env.SLACK_WEBHOOK) {
              await fetch(process.env.SLACK_WEBHOOK, {
                method: 'POST',
                headers: {
                  'Content-Type': 'application/json',
                },
                body: JSON.stringify(slackMessage)
              });
            }
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

  update-existing-issue:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}

    steps:
      - name: Find and update existing issue
        uses: actions/github-script@v7
        with:
          script: |
            const workflowRun = context.payload.workflow_run;
            const searchQuery = `repo:${context.repo.owner}/${context.repo.repo} is:issue is:open label:ci "${workflowRun.name}"`;

            const issues = await github.rest.search.issuesAndPullRequests({
              q: searchQuery
            });

            if (issues.data.items.length > 0) {
              const issue = issues.data.items[0];

              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                body: `🔄 **Nouvel échec détecté**\n\n` +
                      `- **Workflow**: ${workflowRun.name}\n` +
                      `- **Branche**: ${workflowRun.head_branch}\n` +
                      `- **Commit**: ${workflowRun.head_sha.substring(0, 8)}\n` +
                      `- **Heure**: ${workflowRun.updated_at}\n` +
                      `- **Lien**: ${workflowRun.html_url}\n\n` +
                      `*Le problème persiste. Veuillez vérifier les corrections précédentes.*`
              });

              // Ajouter le label "recurring" si ce n'est pas déjà fait
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                labels: ['recurring']
              });

              console.log(`Issue existante mise à jour: ${issue.html_url}`);
            }
