name: 🎯 Automatisation des Issues

on:
  issues:
    types: [opened, labeled, assigned]
  pull_request:
    types: [opened, ready_for_review]

# Ajout des permissions nécessaires
permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  auto-assign-module:
    name: 📋 Attribution automatique par module
    runs-on: ubuntu-latest

    steps:
      - name: Auto-assign based on module label
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            // Vérifier que nous avons une issue (pas une PR)
            if (!context.payload.issue) {
              console.log('Pas une issue, arrêt du workflow');
              return;
            }

            const moduleAssignments = {
              'module:chantiers': ['dev-chantiers'],
              'module:rh': ['dev-rh'],
              'module:commerce': ['dev-commerce'],
              'module:tiers': ['dev-tiers'],
              'module:infrastructure': ['dev-infra'],
              'module:produits-services': ['dev-commerce'],
              'module:gpao': ['dev-production'],
              'module:facturation': ['dev-finance'],
              'transversal:infra': ['devops'],
              'transversal:ux': ['designer']
            };

            const labels = context.payload.issue.labels.map(l => l.name.toLowerCase());
            console.log('Labels détectés (normalisés):', labels);

            for (const [label, assignees] of Object.entries(moduleAssignments)) {
              if (labels.includes(label.toLowerCase())) {
                console.log(`Attribution pour le label ${label}:`, assignees);
                try {
                  await github.rest.issues.addAssignees({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: context.payload.issue.number,
                    assignees: assignees
                  });
                  console.log('Attribution réussie');
                } catch (error) {
                  console.log('Erreur lors de l\'attribution:', error.message);
                }
                break;
              }
            }

  estimate-complexity:
    name: 🎯 Estimation automatique de complexité
    runs-on: ubuntu-latest

    steps:
      - name: Add complexity labels
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            // Vérifier que nous avons une issue (pas une PR)
            if (!context.payload.issue) {
              console.log('Pas une issue, arrêt du workflow');
              return;
            }

            const body = (context.payload.issue.body || '').toLowerCase();
            const title = context.payload.issue.title.toLowerCase();

            let complexity = 'complexity:medium';

            // Mots-clés pour haute complexité
            if (body.includes('migration') || body.includes('api') ||
                body.includes('integration') || title.includes('architecture') ||
                body.includes('base de données') || body.includes('sécurité') ||
                title.includes('refactoring') || body.includes('performance')) {
              complexity = 'complexity:high';
            }

            // Mots-clés pour faible complexité
            if (body.includes('documentation') || body.includes('css') ||
                title.includes('fix') || title.includes('typo') ||
                body.includes('traduction') || title.includes('style') ||
                body.includes('texte') || title.includes('libellé')) {
              complexity = 'complexity:low';
            }

            console.log(`Complexité estimée: ${complexity}`);

            try {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.issue.number,
                labels: [complexity]
              });
              console.log('Label de complexité ajouté avec succès');
            } catch (error) {
              console.log('Erreur lors de l\'ajout du label:', error.message);
            }

  auto-priority:
    name: 🚨 Attribution automatique de priorité
    runs-on: ubuntu-latest

    steps:
      - name: Add priority labels
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            // Vérifier que nous avons une issue (pas une PR)
            if (!context.payload.issue) {
              console.log('Pas une issue, arrêt du workflow');
              return;
            }

            const body = (context.payload.issue.body || '').toLowerCase();
            const title = context.payload.issue.title.toLowerCase();
            const labels = context.payload.issue.labels.map(l => l.name.toLowerCase());

            console.log('Labels détectés (normalisés):', labels);

            let priority = 'priorite:moyenne';

            // Priorité haute pour les bugs critiques
            if (labels.includes('bug') &&
                (body.includes('critique') || body.includes('bloque') ||
                 body.includes('production') || title.includes('urgent'))) {
              priority = 'priorite:haute';
            }

            // Priorité haute pour les fonctionnalités importantes
            if (labels.includes('enhancement') &&
                (body.includes('client') || body.includes('urgent') ||
                 title.includes('important'))) {
              priority = 'priorite:haute';
            }

            // Priorité basse pour la documentation et les améliorations mineures
            if (body.includes('documentation') || title.includes('typo') ||
                title.includes('style') || labels.includes('good first issue')) {
              priority = 'priorite:basse';
            }

            console.log(`Priorité estimée: ${priority}`);

            try {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.issue.number,
                labels: [priority]
              });
              console.log('Label de priorité ajouté avec succès');
            } catch (error) {
              console.log('Erreur lors de l\'ajout du label de priorité:', error.message);
            }
