name: 🎯 Automatisation des Issues

on:
  issues:
    types: [opened, labeled, assigned]
  pull_request:
    types: [opened, ready_for_review]

jobs:
  auto-assign-module:
    name: 📋 Attribution automatique par module
    runs-on: ubuntu-latest

    steps:
      - name: Auto-assign based on module label
        uses: actions/github-script@v7
        with:
          script: |
            const moduleAssignments = {
              'module:produits-services': ['dev-commerce'],
              'module:gpao': ['dev-production'],
              'module:facturation': ['dev-finance'],
              'transversal:infra': ['devops'],
              'transversal:ux': ['designer']
            };

            const labels = context.payload.issue.labels.map(l => l.name);

            for (const [label, assignees] of Object.entries(moduleAssignments)) {
              if (labels.includes(label)) {
                await github.rest.issues.addAssignees({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.payload.issue.number,
                  assignees: assignees
                });
                break;
              }
            }

  estimate-complexity:
    name: 🎯 Estimation automatique de complexité
    runs-on: ubuntu-latest

    steps:
      - name: Add complexity labels
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.issue.body.toLowerCase();
            const title = context.payload.issue.title.toLowerCase();

            let complexity = 'complexity:medium';

            // Mots-clés pour haute complexité
            if (body.includes('migration') || body.includes('api') ||
                body.includes('integration') || title.includes('architecture')) {
              complexity = 'complexity:high';
            }

            // Mots-clés pour faible complexité
            if (body.includes('documentation') || body.includes('css') ||
                title.includes('fix') || title.includes('typo')) {
              complexity = 'complexity:low';
            }

            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              labels: [complexity]
            });
