name: 🚀 Déploiement Module

on:
  push:
    branches: [master, production]
    paths:
      # Modules existants
      - 'app/Models/Chantiers/**'
      - 'app/Models/RH/**'
      - 'app/Models/Tiers/**'
      - 'app/Models/Commerce/**'
      - 'app/Models/Core/**'
      # Modules futurs (patterns génériques)
      - 'app/Models/**'
      - 'app/Livewire/**'
      - 'app/Http/Controllers/**'
      - 'app/Services/**'
      - 'app/Actions/**'
      - 'app/Jobs/**'
      - 'app/Events/**'
      - 'app/Mail/**'
      - 'app/Notifications/**'
      - 'app/Enums/**'
      # Base de données
      - 'database/migrations/**'
      - 'database/factories/**'
      - 'database/seeders/**'
      # Frontend
      - 'resources/views/**'
      - 'resources/js/**'
      - 'resources/css/**'
      # Configuration
      - 'config/**'
      - 'routes/**'

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environnement de déploiement'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
      modules:
        description: 'Modules à déployer (séparés par des virgules, ou "all" pour tous)'
        required: false
        default: 'auto'
        type: string

env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

jobs:
  detect-changes:
    name: 🔍 Détection des Changements
    runs-on: ubuntu-latest
    outputs:
      modules: ${{ steps.detect.outputs.modules }}
      has-migrations: ${{ steps.detect.outputs.has-migrations }}
      has-frontend: ${{ steps.detect.outputs.has-frontend }}
      has-config: ${{ steps.detect.outputs.has-config }}
      deploy-staging: ${{ steps.detect.outputs.deploy-staging }}
      deploy-production: ${{ steps.detect.outputs.deploy-production }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Détecter les modules modifiés
        id: detect
        run: |
          echo "🔍 Détection des changements..."

          # Détection des modules modifiés
          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)
          MODULES=()
          HAS_MIGRATIONS=false
          HAS_FRONTEND=false
          HAS_CONFIG=false

          # Analyse des fichiers modifiés
          while IFS= read -r file; do
            echo "📁 Fichier modifié: $file"

            # Détection des modules
            if [[ $file =~ ^app/Models/([^/]+)/ ]]; then
              MODULE="${BASH_REMATCH[1]}"
              if [[ ! " ${MODULES[@]} " =~ " ${MODULE} " ]]; then
                MODULES+=("$MODULE")
              fi
            elif [[ $file =~ ^app/Livewire/([^/]+)/ ]]; then
              MODULE="${BASH_REMATCH[1]}"
              if [[ ! " ${MODULES[@]} " =~ " ${MODULE} " ]]; then
                MODULES+=("$MODULE")
              fi
            elif [[ $file =~ ^app/(Actions|Services|Jobs|Events|Mail|Notifications|Enums)/([^/]+)/ ]]; then
              MODULE="${BASH_REMATCH[2]}"
              if [[ ! " ${MODULES[@]} " =~ " ${MODULE} " ]]; then
                MODULES+=("$MODULE")
              fi
            fi

            # Détection des types de changements
            if [[ $file =~ ^database/migrations/ ]]; then
              HAS_MIGRATIONS=true
            elif [[ $file =~ ^resources/(views|js|css)/ ]]; then
              HAS_FRONTEND=true
            elif [[ $file =~ ^(config|routes)/ ]]; then
              HAS_CONFIG=true
            fi
          done <<< "$CHANGED_FILES"

          # Gestion du déclenchement manuel
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            if [[ "${{ github.event.inputs.modules }}" == "all" ]]; then
              MODULES=("Chantiers" "RH" "Tiers" "Commerce" "Core")
            elif [[ "${{ github.event.inputs.modules }}" != "auto" ]]; then
              IFS=',' read -ra MODULES <<< "${{ github.event.inputs.modules }}"
            fi
          fi

          # Conversion en JSON
          MODULES_JSON=$(printf '%s\n' "${MODULES[@]}" | jq -R . | jq -s .)

          echo "modules=$MODULES_JSON" >> $GITHUB_OUTPUT
          echo "has-migrations=$HAS_MIGRATIONS" >> $GITHUB_OUTPUT
          echo "has-frontend=$HAS_FRONTEND" >> $GITHUB_OUTPUT
          echo "has-config=$HAS_CONFIG" >> $GITHUB_OUTPUT

          # Déterminer les environnements de déploiement
          if [[ "${{ github.ref }}" == "refs/heads/master" ]] || [[ "${{ github.event.inputs.environment }}" == "staging" ]]; then
            echo "deploy-staging=true" >> $GITHUB_OUTPUT
          else
            echo "deploy-staging=false" >> $GITHUB_OUTPUT
          fi

          if [[ "${{ github.ref }}" == "refs/heads/production" ]] || [[ "${{ github.event.inputs.environment }}" == "production" ]]; then
            echo "deploy-production=true" >> $GITHUB_OUTPUT
          else
            echo "deploy-production=false" >> $GITHUB_OUTPUT
          fi

          echo "📊 Modules détectés: ${MODULES[*]}"
          echo "🗄️ Migrations: $HAS_MIGRATIONS"
          echo "🎨 Frontend: $HAS_FRONTEND"
          echo "⚙️ Config: $HAS_CONFIG"

  deploy-staging:
    name: 📦 Déploiement Staging
    runs-on: ubuntu-latest
    environment: staging
    needs: detect-changes
    if: needs.detect-changes.outputs.deploy-staging == 'true' && needs.detect-changes.outputs.modules != '[]'

    strategy:
      matrix:
        module: ${{ fromJson(needs.detect-changes.outputs.modules) }}
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, iconv, json, mbstring, pdo

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Préparer l'environnement
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Exécuter les migrations
        if: needs.detect-changes.outputs.has-migrations == 'true'
        run: |
          echo "🗄️ Exécution des migrations pour le module ${{ matrix.module }}"
          php artisan migrate --force

      - name: Compiler les assets
        if: needs.detect-changes.outputs.has-frontend == 'true'
        run: |
          echo "🎨 Compilation des assets frontend"
          npm ci
          npm run build

      - name: Déployer le module ${{ matrix.module }}
        run: |
          echo "🚀 Déploiement du module ${{ matrix.module }} sur staging"

          # Vider les caches
          php artisan cache:clear
          php artisan config:clear
          php artisan route:clear
          php artisan view:clear

          # Optimiser pour la production
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

          # Publier les assets si nécessaire
          php artisan vendor:publish --tag=public --force

          # Redémarrer les queues si elles existent
          php artisan queue:restart || true

      - name: Tests de fumée
        run: |
          echo "🧪 Tests de fumée pour le module ${{ matrix.module }}"

          # Tests basiques de l'application
          php artisan test --testsuite=Feature --stop-on-failure

          # Vérifier que l'application répond
          php artisan route:list | grep -i ${{ matrix.module }} || echo "Aucune route spécifique au module trouvée"

      - name: Vérification de santé
        run: |
          echo "❤️ Vérification de santé du module ${{ matrix.module }}"

          # Vérifier la connectivité à la base de données
          php artisan migrate:status

          # Vérifier les services essentiels
          php artisan about --only=environment,cache,database

          # Test de santé personnalisé si disponible
          php artisan health:check || echo "Commande health:check non disponible"
          # Tests basiques post-déploiement
          # php artisan test --filter=${{ matrix.module }}

      - name: Vérification de santé
        run: |
          echo "❤️ Vérification de santé du module ${{ matrix.module }}"
          # Vérifications de santé spécifiques
          # curl -f http://staging.example.com/health/${{ matrix.module }}

  notify-staging:
    name: 📢 Notification Staging
    runs-on: ubuntu-latest
    needs: [detect-changes, deploy-staging]
    if: always() && needs.detect-changes.outputs.deploy-staging == 'true'

    steps:
      - name: Notifier l'équipe
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ env.SLACK_WEBHOOK }}
          SLACK_MESSAGE: |
            ${{ needs.deploy-staging.result == 'success' && '✅' || '❌' }} Déploiement Staging

            **Modules:** ${{ join(fromJson(needs.detect-changes.outputs.modules), ', ') }}
            **Migrations:** ${{ needs.detect-changes.outputs.has-migrations == 'true' && '✅' || '❌' }}
            **Frontend:** ${{ needs.detect-changes.outputs.has-frontend == 'true' && '✅' || '❌' }}
            **Config:** ${{ needs.detect-changes.outputs.has-config == 'true' && '✅' || '❌' }}

            ${{ needs.deploy-staging.result == 'success' && 'Prêt pour validation et déploiement production' || 'Échec du déploiement - Vérification requise' }}

  deploy-production:
    name: 🏭 Déploiement Production
    runs-on: ubuntu-latest
    environment: production
    needs: [detect-changes, deploy-staging]
    if: |
      needs.detect-changes.outputs.deploy-production == 'true' &&
      needs.detect-changes.outputs.modules != '[]' &&
      (needs.deploy-staging.result == 'success' || needs.detect-changes.outputs.deploy-staging == 'false')

    strategy:
      matrix:
        module: ${{ fromJson(needs.detect-changes.outputs.modules) }}
      fail-fast: true

    steps:
      - name: Approbation manuelle requise
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: vortechstudio
          minimum-approvals: 1
          issue-title: "🏭 Déploiement Production - Module ${{ matrix.module }}"
          issue-body: |
            ## 🚀 Demande de déploiement en production

            **Module:** ${{ matrix.module }}
            **Commit:** ${{ github.sha }}
            **Auteur:** ${{ github.actor }}

            ### Changements détectés:
            - **Migrations:** ${{ needs.detect-changes.outputs.has-migrations == 'true' && '✅ Oui' || '❌ Non' }}
            - **Frontend:** ${{ needs.detect-changes.outputs.has-frontend == 'true' && '✅ Oui' || '❌ Non' }}
            - **Configuration:** ${{ needs.detect-changes.outputs.has-config == 'true' && '✅ Oui' || '❌ Non' }}

            ### Vérifications pré-déploiement:
            - [ ] Tests de staging validés
            - [ ] Documentation mise à jour
            - [ ] Équipe notifiée
            - [ ] Backup effectué

            **Approuvez ce déploiement pour continuer.**

      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, iconv, json, mbstring, pdo

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --optimize-autoloader

      - name: Backup avant déploiement
        run: |
          echo "💾 Backup de la base de données avant déploiement"
          # Commandes de backup

      - name: Déployer en production
        run: |
          echo "🏭 Déploiement du module ${{ matrix.module }} en production"

          # Mode maintenance
          php artisan down --message="Déploiement en cours..." --retry=60

          # Vider tous les caches
          php artisan cache:clear
          php artisan config:clear
          php artisan route:clear
          php artisan view:clear
          php artisan event:clear

          # Optimisations production
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          php artisan event:cache

          # Optimiser l'autoloader Composer
          composer dump-autoload --optimize

          # Publier les assets
          php artisan vendor:publish --tag=public --force

          # Redémarrer les services
          php artisan queue:restart || true
          php artisan schedule:clear-cache || true

          # Sortir du mode maintenance
          php artisan up

      - name: Tests post-déploiement
        run: |
          echo "🧪 Tests post-déploiement en production"

          # Tests critiques uniquement
          php artisan test --testsuite=Feature --group=critical --stop-on-failure || true

          # Vérifier les routes principales
          php artisan route:list --compact

      - name: Vérification finale
        run: |
          echo "✅ Vérification finale du déploiement"

          # Statut des migrations
          php artisan migrate:status

          # Informations système
          php artisan about --only=environment,cache,database

          # Vérifier les permissions de stockage
          php artisan storage:link || echo "Storage link déjà créé"

          # Test de santé final
          php artisan inspire # Commande simple pour vérifier que Laravel fonctionne

  notify-production:
    name: 📢 Notification Production
    runs-on: ubuntu-latest
    needs: [detect-changes, deploy-production]
    if: always() && needs.detect-changes.outputs.deploy-production == 'true'

    steps:
      - name: Notifier l'équipe
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ env.SLACK_WEBHOOK }}
          SLACK_MESSAGE: |
            ${{ needs.deploy-production.result == 'success' && '🎉' || '🚨' }} Déploiement Production

            **Modules:** ${{ join(fromJson(needs.detect-changes.outputs.modules), ', ') }}
            **Statut:** ${{ needs.deploy-production.result == 'success' && 'Succès' || 'Échec' }}
            **Commit:** ${{ github.sha }}
            **Auteur:** ${{ github.actor }}

            ${{ needs.deploy-production.result == 'success' && '✅ Déploiement terminé avec succès' || '❌ Échec du déploiement - Intervention requise' }}
