name: Generate PR Description

on:
  pull_request:
    types: [opened, edited, synchronize]
    branches:
      - master

jobs:
  generate-description:
    runs-on: ubuntu-latest
    steps:
      - name: Generate PR description
        uses: tibdex/pull-request-changelog@main
        with:
          config: |
            configuration: |
              exclude:
                - chore
                - docs
              template: |
                ## Changements
                $CHANGES
                
                ## Types de commits
                $CATEGORIES