name: Generate PR Description

on:
  pull_request:
    types: [opened, edited, synchronize]
    branches:
      - master

jobs:
  generate-description:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Récupération des commits du PR
        id: commits
        run: |
          COMMITS=$(gh pr view ${{ github.event.pull_request.number }} --repo ${{ github.repository }} --json commits | jq -r '.commits[].messageHeadline // empty')
          echo "commit_messages<<EOF" >> $GITHUB_ENV
          echo "$COMMITS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Génération du résumé avec Ollama server
        id: ollama
        run: |
          RESPONSE=$(curl -s http://86.217.43.98:11434/api/generate \
            -H "Content-Type: application/json" \
            -d '{
              "model": "deepseeker-r1",
              "prompt": "Voici la liste des messages de commit pour une pull request GitHub :\n\n${{ env.commit_messages }}\n\nGénère un résumé clair en français, en quelques lignes, de ce que cette PR contient.",
              "stream": false
            }')

          SUMMARY=$(echo "$RESPONSE" | jq -r '.response')
          echo "summary<<EOF" >> $GITHUB_ENV
          echo "$SUMMARY" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Mise à jour de la PR
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --body "${{ env.summary }}"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
