name: Security Scan

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]
  schedule:
    - cron: '0 2 * * 1' # Lundi à 2h

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Composer Audit
        run: composer audit

      - name: Run NPM Audit
        run: npm audit --audit-level=moderate

      - name: Security Headers Check
        run: |
          # Vérifier les headers de sécurité avec gestion d'erreur
          echo "🔍 Vérification des headers de sécurité..."

          # Définir l'URL à tester
          URL="https://beta.batistack.ovh"

          # Tester la connectivité d'abord
          if curl -s --connect-timeout 10 --max-time 30 -f "$URL" > /dev/null; then
            echo "✅ Site accessible : $URL"

            # Récupérer les headers
            HEADERS=$(curl -I -s --connect-timeout 10 --max-time 30 "$URL" 2>/dev/null)

            if [ $? -eq 0 ]; then
              echo "📋 Headers reçus :"
              echo "$HEADERS"
              echo ""

              # Vérifier les headers de sécurité spécifiques
              echo "🔒 Vérification des headers de sécurité :"

              # X-Frame-Options
              if echo "$HEADERS" | grep -qi "X-Frame-Options"; then
                echo "✅ X-Frame-Options: $(echo "$HEADERS" | grep -i "X-Frame-Options" | head -1)"
              else
                echo "❌ X-Frame-Options: MANQUANT"
              fi

              # X-Content-Type-Options
              if echo "$HEADERS" | grep -qi "X-Content-Type-Options"; then
                echo "✅ X-Content-Type-Options: $(echo "$HEADERS" | grep -i "X-Content-Type-Options" | head -1)"
              else
                echo "❌ X-Content-Type-Options: MANQUANT"
              fi

              # Strict-Transport-Security
              if echo "$HEADERS" | grep -qi "Strict-Transport-Security"; then
                echo "✅ Strict-Transport-Security: $(echo "$HEADERS" | grep -i "Strict-Transport-Security" | head -1)"
              else
                echo "❌ Strict-Transport-Security: MANQUANT"
              fi

              # Content-Security-Policy
              if echo "$HEADERS" | grep -qi "Content-Security-Policy"; then
                echo "✅ Content-Security-Policy: $(echo "$HEADERS" | grep -i "Content-Security-Policy" | head -1)"
              else
                echo "❌ Content-Security-Policy: MANQUANT"
              fi

              # X-XSS-Protection
              if echo "$HEADERS" | grep -qi "X-XSS-Protection"; then
                echo "✅ X-XSS-Protection: $(echo "$HEADERS" | grep -i "X-XSS-Protection" | head -1)"
              else
                echo "❌ X-XSS-Protection: MANQUANT"
              fi

            else
              echo "❌ Erreur lors de la récupération des headers"
              exit 1
            fi
          else
            echo "❌ Site non accessible : $URL"
            echo "⚠️  Vérification des headers de sécurité ignorée (site non accessible)"
            # Ne pas faire échouer le workflow si le site n'est pas accessible
            exit 0
          fi

      - name: OWASP ZAP Baseline Scan
        if: github.event_name != 'pull_request'
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'https://beta.batistack.ovh'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
        continue-on-error: true

      - name: Upload ZAP Report
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: report_html.html
        continue-on-error: true
