name: Test sur master
on:
  push:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.3

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: pdo_mysql, mbstring

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Configure Laravel
        run: |
          cp .env.github .env
          php artisan key:generate

      - name: Run NPM Build Frontend Env
        run: |
          npm install
          npm run build

      - name: Run migrations
        run: php artisan migrate --force

      - name: Run tests
        run: php artisan test --parallel

      - name: Création ticket GitHub
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '[CI] Échec des tests sur main - ' + new Date().toISOString(),
              body: `### Échec des tests sur la branche main

      **Contexte** :
      - Workflow: ${{ github.workflow }}
      - Commit: ${{ github.sha }}

      **Résultats des tests** :
      \\`\\`\\`
      ${{ env.TEST_RESULTS }}
      \\`\\`\\`

      **Checklist investigation** :
      \\`\\`\\`
      [x] Vérifier les logs du workflow
      [x] Reproduire localement
      [ ] Analyser les changements récents
      \\`\\`\\`

      **Assignation automatique** :
      @tech-lead @devops`,
              labels: ['bug', 'ci'],
              assignees: ['tech-lead']
            })
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TEST_RESULTS: ${{ steps.run-tests.outputs.error }}
