name: Test sur master
on:
  push:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: sqlite

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Configure Laravel
        run: |
          cp .env.github .env
          php artisan key:generate

      - name: Run migrations
        run: php artisan migrate --force

      - name: Run tests
        run: php artisan test --parallel
