name: Test sur master
on:
  push:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.3

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: pdo_sqlite, mbstring, sqlite3

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Configure Laravel
        run: |
          cp .env.github .env
          php artisan key:generate

      - name: Write secrets to .env
        run: |
          echo "BRIDGE_CLIENT_ID=${{ secrets.BRIDGE_CLIENT_ID }}" >> .env
          echo "BRIDGE_CLIENT_SECRET=${{ secrets.BRIDGE_CLIENT_SECRET }}" >> .env

      - name: Run NPM Build Frontend Env
        run: |
          npm install
          npm run build

      - name: Run migrations
        run: php artisan migrate --force

      - name: Run tests
        run: php artisan test --parallel --coverage-clover=coverage.xml --log-junit junit.xml

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage.xml
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          files: junit.xml
          token: ${{ secrets.CODECOV_TOKEN }}

