name: Test sur master
on:
  push:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.3

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: pdo_sqlite, mbstring, sqlite3

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Configure Laravel
        run: |
          cp .env.github .env
          php artisan key:generate

      - name: Run NPM Build Frontend Env
        run: |
          npm install
          npm run build

      - name: Run migrations
        run: php artisan migrate --force

      - name: Run tests
        run: php artisan test --parallel --coverage-clover=coverage.xml

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage.xml
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Create Issue on Failure
        if: failure()
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "🚨 CI Failed on ${{ github.workflow }} (#${{ github.run_number }})"
          content-filepath: .github/ISSUE_TEMPLATE/ci-failure.md
          labels: |
            bug
            CI
          assignees: vortechstudio
          token: ${{ secrets.GH_TOKEN }}
