name: Test sur master
on:
  push:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.3

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: pdo_mysql, mbstring

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Configure Laravel
        run: |
          cp .env.github .env
          php artisan key:generate

      - name: Run NPM Build Frontend Env
        run: |
          npm install
          npm run build

      - name: Run migrations
        run: php artisan migrate --force

      - name: Run tests
        run: php artisan test --parallel

      - name: Create Github issue on failure
        if: failure
        uses: actions/github-script@v7
        with:
        script: |
          await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: `Échec des tests sur master - ${new Date().toISOString()}`,
            labels: ['bug', 'ci'],
            body: `Workflow en échec : ${process.env.GITHUB_WORKFLOW}

**Détails :**
- Lien du workflow: ${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}
- Commit: ${process.env.GITHUB_SHA}

**Étapes à suivre :**
- [ ] Vérifier les logs du workflow
- [ ] Reproduire localement
- [ ] Corriger les tests`,
            labels: ['bug', 'ci']
          })
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
